# Generated by Django 3.1.7 on 2021-03-18 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EndCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Numele orasului')),
                ('popular', models.BooleanField(default=True, verbose_name='Alesul')),
            ],
            options={
                'verbose_name': 'Punct de sosire',
                'verbose_name_plural': 'Puncte de sosire',
            },
        ),
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_center_trip', models.CharField(max_length=255, verbose_name='Oraș intermediar')),
                ('all_city_trip', models.TextField(max_length=255, verbose_name='Toate orașele călătoresc')),
                ('date_trip', models.DateField(verbose_name='Data plecării')),
                ('time_trip', models.TimeField(verbose_name='Timp de plecare')),
                ('date_trip_end', models.DateTimeField(verbose_name='Data și ora sosirii')),
                ('type_of_transport', models.CharField(choices=[('Autocar', 'Autocar'), ('Microbuze', 'Microbuze')], max_length=255, verbose_name='Tipul de transport')),
                ('model_of_transport', models.CharField(max_length=255, verbose_name='Model de transport')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Prețul biletului')),
                ('qty_of_seats', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Locuri rămase')),
                ('image', models.ImageField(upload_to='', verbose_name='Imagine')),
                ('active', models.BooleanField(default=True, verbose_name='Activ')),
                ('transfer', models.CharField(max_length=255, verbose_name='Transportator')),
                ('city_end_trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.endcity', verbose_name='Punct de sosire')),
            ],
            options={
                'verbose_name': 'Calatoria',
                'verbose_name_plural': 'Traseu',
            },
        ),
        migrations.CreateModel(
            name='StartCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Numele orasului')),
                ('popular', models.BooleanField(default=True, verbose_name='Alesul')),
            ],
            options={
                'verbose_name': 'Punct de plecare',
                'verbose_name_plural': 'Puncte de plecare',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Număr de telefon')),
                ('email', models.CharField(max_length=255, verbose_name='E-mail')),
                ('passenger1_name', models.CharField(max_length=255, verbose_name='Numele primului pasager')),
                ('passenger1_second_name', models.CharField(max_length=255, verbose_name='Numele primului pasager')),
                ('passenger1_passport_type', models.CharField(choices=[('EU', 'EU'), ('MD', 'MD')], max_length=255, verbose_name='Tipul pașaportului')),
                ('passenger2_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Al doilea nume pasager')),
                ('passenger2_second_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Numele celui de-al doilea pasager')),
                ('passenger2_passport_type', models.CharField(blank=True, choices=[('EU', 'EU'), ('MD', 'MD')], max_length=255, null=True, verbose_name='Tipul pașaportului')),
                ('passenger3_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Al treilea nume al pasagerului')),
                ('passenger3_second_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Numele celui de-al treilea pasager')),
                ('passenger3_passport_type', models.CharField(blank=True, choices=[('EU', 'EU'), ('MD', 'MD')], max_length=255, null=True, verbose_name='Tipul pașaportului')),
                ('passenger4_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Numele celui de-al patrulea pasager')),
                ('passenger4_second_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Numele celui de-al patrulea pasager')),
                ('passenger4_passport_type', models.CharField(blank=True, choices=[('EU', 'EU'), ('MD', 'MD')], max_length=255, null=True, verbose_name='Tipul pașaportului')),
                ('passenger5_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Numele celui de-al cincilea pasager')),
                ('passenger5_second_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Numele celui de-al cincilea pasager')),
                ('passenger5_passport_type', models.CharField(blank=True, choices=[('EU', 'EU'), ('MD', 'MD')], max_length=255, null=True, verbose_name='Tipul pașaportului')),
                ('passenger6_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Numele celui de-al șaselea pasager')),
                ('passenger6_second_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Numele celui de-al șaselea pasager')),
                ('passenger6_passport_type', models.CharField(blank=True, choices=[('EU', 'EU'), ('MD', 'MD')], max_length=255, null=True, verbose_name='Tipul pașaportului')),
                ('passenger7_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Numele celui de-al șaptelea pasager')),
                ('passenger7_second_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Numele celui de-al șaptelea pasager')),
                ('passenger7_passport_type', models.CharField(blank=True, choices=[('EU', 'EU'), ('MD', 'MD')], max_length=255, null=True, verbose_name='Tipul pașaportului')),
                ('passenger8_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Numele celui de-al optulea pasager')),
                ('passenger8_second_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Numele celui de-al optulea pasager')),
                ('passenger8_passport_type', models.CharField(blank=True, choices=[('EU', 'EU'), ('MD', 'MD')], max_length=255, null=True, verbose_name='Tipul pașaportului')),
                ('passenger9_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Numele celui de-al nouălea pasager')),
                ('passenger9_second_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Numele celui de-al nouălea pasager')),
                ('passenger9_passport_type', models.CharField(blank=True, choices=[('EU', 'EU'), ('MD', 'MD')], max_length=255, null=True, verbose_name='Tipul pașaportului')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Cost total')),
                ('status', models.CharField(choices=[('new', 'Comandă nouă'), ('completed', 'Achitat')], default='new', max_length=100, verbose_name='Stare')),
                ('payment_type', models.CharField(choices=[('card', 'Plata cu cardul'), ('terminal', 'Plata prin terminal Cash')], default='card', max_length=100, verbose_name='Modalitate de plată')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Data creării comenzii')),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.journey', verbose_name='Calatoria')),
            ],
            options={
                'verbose_name': 'Ordin',
                'verbose_name_plural': 'Comenzi',
            },
        ),
        migrations.AddField(
            model_name='journey',
            name='city_start_trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.startcity', verbose_name='Punct de plecare'),
        ),
    ]
