# Generated by Django 3.1.7 on 2021-04-09 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateMarker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Дата',
                'verbose_name_plural': 'Даты',
            },
        ),
        migrations.CreateModel(
            name='TimeTrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_trip', models.TimeField(verbose_name='Время')),
            ],
            options={
                'verbose_name': 'Время',
                'verbose_name_plural': 'Время',
            },
        ),
        migrations.RemoveField(
            model_name='journey',
            name='date_trip_end',
        ),
        migrations.RemoveField(
            model_name='journey',
            name='qty_of_seats',
        ),
        migrations.AddField(
            model_name='journey',
            name='time_in_journey',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Timp de calatorie'),
        ),
        migrations.AddField(
            model_name='order',
            name='date_of_journey',
            field=models.DateField(blank=True, null=True, verbose_name='Data călătoriei'),
        ),
        migrations.AddField(
            model_name='order',
            name='time_of_journey',
            field=models.TimeField(blank=True, null=True, verbose_name='Timp de calatorie'),
        ),
        migrations.RemoveField(
            model_name='journey',
            name='date_trip',
        ),
        migrations.AlterField(
            model_name='journey',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagine'),
        ),
        migrations.RemoveField(
            model_name='journey',
            name='time_trip',
        ),
        migrations.AddField(
            model_name='journey',
            name='date_trip',
            field=models.ManyToManyField(to='main.DateMarker', verbose_name='Data plecării'),
        ),
        migrations.AddField(
            model_name='journey',
            name='time_trip',
            field=models.ManyToManyField(to='main.TimeTrip', verbose_name='Timp de plecare'),
        ),
    ]
