# Generated by Django 3.1.7 on 2021-04-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210409_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularTrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_city_popular_trip', models.CharField(max_length=255, verbose_name='Plecare')),
                ('end_city_popular_trip', models.CharField(max_length=255, verbose_name='Sosire')),
                ('image', models.ImageField(upload_to='', verbose_name='Imagine')),
                ('active', models.BooleanField(default=True, verbose_name='Activ')),
            ],
            options={
                'verbose_name': 'Traseu popular',
                'verbose_name_plural': 'Trasee populare',
            },
        ),
    ]
