# Generated by Django 3.1.7 on 2021-04-16 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_populartrip'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelOfTransport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Model de transport')),
            ],
            options={
                'verbose_name': 'Model de transport',
                'verbose_name_plural': 'Modele de transport',
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Transportator')),
            ],
            options={
                'verbose_name': 'Transportator',
                'verbose_name_plural': 'Transportatori',
            },
        ),
        migrations.AlterModelOptions(
            name='datemarker',
            options={'verbose_name': 'Data', 'verbose_name_plural': 'Datele'},
        ),
        migrations.AlterModelOptions(
            name='timetrip',
            options={'verbose_name': 'Timp', 'verbose_name_plural': 'Timpul'},
        ),
        migrations.AlterField(
            model_name='journey',
            name='date_trip',
            field=models.ManyToManyField(related_name='journey_date_marker', to='main.DateMarker', verbose_name='Data plecării'),
        ),
        migrations.AlterField(
            model_name='journey',
            name='time_trip',
            field=models.ManyToManyField(related_name='journey_marker', to='main.TimeTrip', verbose_name='Timp de plecare'),
        ),
        migrations.AlterField(
            model_name='populartrip',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagine'),
        ),
        migrations.AlterField(
            model_name='journey',
            name='model_of_transport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.modeloftransport', verbose_name='Model de transport'),
        ),
        migrations.AlterField(
            model_name='journey',
            name='transfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.transfer', verbose_name='Transportator'),
        ),
    ]
