# Generated by Django 3.1.7 on 2021-04-20 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210416_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='populartrip',
            name='end_city_popular_trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.endcity', verbose_name='Sosire'),
        ),
        migrations.AlterField(
            model_name='populartrip',
            name='start_city_popular_trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.startcity', verbose_name='Plecare'),
        ),
    ]
